### ISSUE TITLE
substBMA broken due to core change

### ISSUE THREAD

**Issue by walterxie** [jessiewu/substBMA#3]
When I compared the result of *rdpm* examples in substBMA using BEAST 2.5 with one using BEAST 2.4 recently, I found the “rates.pointers” always had 1 more value in every dimensions using BEAST 2.5  than BEAST 2.4. 

<img width="300" alt="rates.pointers" src="https://user-images.githubusercontent.com/5743014/42851730-ce025d04-8a81-11e8-9506-1b651892352f.png">

I also found all *sdpm1* and *sdpm2* examples throwing `ArrayIndexOutOfBoundsException` caused by passing -1 index to array. So, I spent a couple of days to locate the problem:   
 
The BEAST core function `ParametricDistribution.sample` was changed due to issue https://github.com/CompEvol/beast2/issues/658, which affected all classes in substBMA to use the _offset_, which especially distorted the index of models (`modelList` in XML). I suspect this would be the same cause to increase 1 more value in the “rates.pointers”.

<img width="600" alt="change" src="https://user-images.githubusercontent.com/5743014/42852013-c5648e46-8a82-11e8-9291-ba99ea085e5e.png">

<img width="300" alt="classes" src="https://user-images.githubusercontent.com/5743014/42852016-c840f99c-8a82-11e8-98d9-705f669d9c27.png">

**Comment by walterxie** [comment]
The implementation of [CategoricalDistribution$CategoricalImpl](https://github.com/jessiewu/substBMA/blob/master/src/beast/math/distributions/CategoricalDistribution.java) uses offseted value as the array index of `prob[]`. After fixing CompEvol/beast2#658, [ParametricDistribution](https://github.com/CompEvol/beast2/blob/master/src/beast/math/distributions/ParametricDistribution.java)#sample(int) does not handle `offset` anymore. This change made model indexes incorrectly mapping to probabilities if model indexes didn't start from 0.

Firstly, I refactor most sampling code into samplers created in [QuietRealParameter](https://github.com/jessiewu/substBMA/blob/master/src/beast/core/parameter/QuietRealParameter.java). Secondly, I add the `offset` to sampled values only when the distribution is [IntegerDistribution](https://github.com/CompEvol/beast2/blob/master/src/org/apache/commons/math/distribution/IntegerDistribution.java).

**Comment by walterxie** [comment]
It looks the problem solved. The fixed code (2.5) provides the exactly same result using _rdpm_ to 2.4.8 (_sdpm1_ and _sdpm2_ were not working in 2.4.8).

Posterior:
<img width="360" alt="Posterior" src="https://user-images.githubusercontent.com/5743014/43231167-58d6e51a-90bf-11e8-84b2-1fca6bedade5.png">

The lengths of all indexes are same:
<img width="1200" alt="indexes" src="https://user-images.githubusercontent.com/5743014/43231172-5e53ae7e-90bf-11e8-9cf1-39345b76ba4e.png">

**Comment by walterxie** [comment]
I also tested _sdpm1_ and _sdpm2_ XMLs, both completed. 
@jessiewu 
Do you have any favoured XML as the example? I saw [mammal_sdpm2_sc.xml](
https://github.com/jessiewu/substBMA/blob/master/examples/mammal/mammal_sdpm2_sc.xml) was chosen in https://www.beast2.org/features/.

**Comment by jessiewu** [comment]
Hi Walter, 

Thats wonderful, thank you very much!

Yes the mammal dataset has been chosen for a lot of the demonstrations because it's small enough to run the analyses within a short period of time. If you have time and would like to test the bug fix on other data sets, I would recommend the RSVA xmls in the folder /example/rsva/. That's the smallest virus dataset in the example folder. If that works, then we shouldn't have to worry about the other virus examples.

Many thanks again for your help!

**Comment by walterxie** [comment]
@jessiewu 
I think RSVA xmls work:
this is same to the orange bars in your paper fig1.

<img width="1312" alt="Screen Shot 2019-07-02 at 12 22 03 PM" src="https://user-images.githubusercontent.com/5743014/60474401-d9ea1d80-9cc5-11e9-94bf-0d4d20f7bab0.png">

**Comment by jessiewu** [comment]
@walterxie 

Thanks a lot for the information! Sorry I didn't mean to create more work for you. I think I did check to see if the estimates were right. I hadn't closed the issue and not made the appropriate release simply because I just ......... forgot(!!!). Sorry, it's been quite a while that I've had to do beast package logistics. Anyhow, thank you so much for all your help!

Jessie
